basePath: /
definitions:
  models.Item:
    properties:
      description:
        example: A random description
        type: string
      itemCode:
        example: ic-123
        type: string
      lineItemId:
        example: 1
        type: integer
      quantity:
        example: 1
        type: integer
    required:
    - description
    - itemCode
    - lineItemId
    - quantity
    type: object
  models.Order:
    properties:
      customerName:
        type: string
      items:
        items:
          $ref: '#/definitions/models.Item'
        type: array
      orderId:
        type: integer
      orderedAt:
        type: string
    required:
    - customerName
    - items
    - orderId
    - orderedAt
    type: object
host: localhost:8080
info:
  contact:
    email: musthafafaisha@gmail.com
    name: musshal
  description: Simple Orders API
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms
  title: Orders API
  version: 1.0.0
paths:
  /orders:
    delete:
      consumes:
      - application/json
      description: Delete order
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete order
      tags:
      - orders
    get:
      consumes:
      - application/json
      description: Get details of all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
      summary: Get details of all orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create new order
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
      summary: Create new order
      tags:
      - orders
    put:
      consumes:
      - application/json
      description: Update order
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
      summary: Update order
      tags:
      - orders
swagger: "2.0"
